#--------------------------------------------------------------
# This is a basic workflow to help you get started with Actions
#--------------------------------------------------------------

name: front-project-lvl1-basics


on: [push]
  
jobs:
 linting_repository:
  
  runs-on: ubuntu-latest

  steps:
  - name: git clone my repository
    uses: actions/checkout@v1

  - name: linting(ESLINT)
    run: make lint
